# Configuration de base pour Air (hot reload)
# Documentation : https://github.com/air-verse/air

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = ""
  include_ext = [".go"]
  exclude_dir = ["bin", "static", "template", "tmp"]
  exclude_file = []
  exclude_regex = []
  follow_symlink = false
  dir = "."

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true

[debug]
  enable = false

[run]
  cmd = ""
  args = []
  env = ["PORT=8080"]
  env_file = ".env"
  delay = 0
  grace = 500
  watch_dir = "."
  watch_ext = [".go"]
  watch_exclude_dir = ["bin", "static", "template", "tmp"]
  watch_exclude_file = []
  watch_exclude_regex = []
  follow_symlink = false
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500
